DROP TABLE IF EXISTS athlete_time_inputs CASCADE;
DROP TABLE IF EXISTS athlete_rest_inputs CASCADE;
DROP TABLE IF EXISTS athlete_note_inputs CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS user_relations CASCADE;