services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    user: root
    ports:
      - 8000:8000
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -dbPath /home/dynamodblocal/data -sharedDb"
    

volumes:
  dynamodb-data: