services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trackme
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"
    volumes:
      - dynamodb:/home/dynamodblocal/data
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
volumes:
  pgdata:
  dynamodb: