AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CreateAthleteFunction:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: lambdas/athletes/create_athlete/
        Handler: create_athlete.create_athlete
        Runtime: python3.12

