AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DynamoDBLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: DynamoDBLayer
        Description: DynamoDBLayer utilities
        ContentUri: layers/common/  # directory containing the layer content
        CompatibleRuntimes:
          - python3.12
  CreateAthleteFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambdas/athlete/create_athlete/
      Handler: create_athlete.create_athlete
      Runtime: python3.12
      Timeout: 15
      Environment:
        Variables:
          DYNAMODB_ENDPOINT_URL: http://host.docker.internal:8000
      Events:
        CreateAthleteApi:
          Type: Api
          Properties:
            Path: /athletes/create_athlete/
            Method: post
      Layers:
        - Ref: CommonLayer