AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    Environment:
      Variables:
        RDS_ENDPOINT: host.docker.internal
        RDS_PORT: 5433
        RDS_USER: postgres
        RDS_DBNAME: trackme
        RDS_PASSWORD: password
        DYNAMODB_ENDPOINT: http://host.docker.internal:8001
        DYNAMODB_REGION: us-west-1
        AWS_ACCESS_KEY_ID: fakeAccessKeyId
        AWS_SECRET_ACCESS_KEY: fakeSecretAccessKey


Resources:
  # API Gateway
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowHeaders: "'Content-Type, Authorization'"
        AllowOrigin: "'http://localhost:8081'"
        AllowCredentials: true
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub "arn here"
            Identity:
              Header: Authorization

  RDSLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: RDSLayer
      Description: RDSLayer utilities
      ContentUri: layers/rds/python/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

  UserAuthLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: UserAuthLayer
      Description: UserAuthLayer utilities
      ContentUri: layers/user_auth/python/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12
  #
  #
  #
  # ATHLETE FUNCTIONS
  #
  #
  #
  RemoveInputsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/athlete/remove_inputs/
      Handler: remove_inputs.remove_inputs
      Events:
        RemoveInputsApi:
          Type: Api
          Properties: 
            Path: /athletes/remove_inputs/
            Method: post
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  SearchInputHistoryDateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/athlete/search_input_history_date/
      Handler: search_input_history_date.search_input_history_date
      Events:
        SearchInputHistoryDateApi:
          Type: Api
          Properties:
            Path: /athletes/search_input_history_date/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  InputTimesFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambdas/athlete/input_times/
      Handler: input_times.input_times
      Events:
        InputTimeApi:
          Type: Api
          Properties:
            Path: /athletes/input_times/
            Method: post
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  ViewWorkoutInputsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambdas/athlete/view_workout_inputs/
      Handler: view_workout_inputs.view_workout_inputs
      Events:
        ViewWorkoutInputsApi:
          Type: Api
          Properties:
            Path: /athletes/view_workout_inputs/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer
  #
  #
  #
  # GENERAL FUNCTIONS
  #
  #
  #
  GetMutualInputsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/general/get_mutual_inputs/
      Handler: get_mutual_inputs.get_mutual_inputs
      Events:
        GetMutualInputsApi:
          Type: Api
          Properties:
            Path: /general/get_mutual_inputs/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  UpdateUserProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/general/update_user_profile/
      Handler: update_user_profile.update_user_profile
      Events:
        UpdateUserProfileApi:
          Type: Api
          Properties:
            Path: /general/update_user_profile/
            Method: post
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/general/create_user/
      Handler: create_user.create_user
      Events:
        CreateUserApi:
          Type: Api
          Properties:
            Path: /general/create_user/
            Method: post
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  MassInput:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/general/mass_input/
      Handler: mass_input.mass_input
      Events:
        MassInputApi:
          Type: Api
          Properties:
            Path: /general/mass_input/
            Method: post
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/general/get_user/
      Handler: get_user.get_user
      Events:
        GetUserApi:
          Type: Api
          Properties:
            Path: /general/get_user/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  #
  #
  #
  # HISTORY FUNCTIONS
  #
  #
  #
  GetEarliestDateAvailableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/history/get_earliest_date_available/
      Handler: get_earliest_date_available.get_earliest_date_available
      Events:
        GetEarliestDateAvailableApi:
          Type: Api
          Properties:
            Path: /history/get_earliest_date_available/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  FetchHistoricalDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/history/fetch_historical_data/
      Handler: fetch_historical_data.fetch_historical_data
      Events:
        FetchHistoricalDataApi:
          Type: Api
          Properties:
            Path: /history/fetch_historical_data/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  GetAvailableHistoryDatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/history/get_available_history_dates/
      Handler: get_available_history_dates.get_available_history_dates
      Events:
        GetAvailableHistoryDatesApi:
          Type: Api
          Properties:
            Path: /history/get_available_history_dates/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  #
  #
  #
  # RELATIONS FUNCTIONS
  #
  #
  #

  GetMutualAthletesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/relations/get_mutual_athletes/
      Handler: get_mutual_athletes.get_mutual_athletes
      Events:
        GetMutualAthletesApi:
          Type: Api
          Properties:
            Path: /relations/get_mutual_athletes/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  AddRelationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/relations/add_relation/
      Handler: add_relation.add_relation
      Events:
        AddRelationApi:
          Type: Api
          Properties:
            Path: /relations/add_relation/
            Method: post
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer
    
  SearchUserRelationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/relations/search_user_relation/
      Handler: search_user_relation.search_user_relation
      Events:
        SearchUserRelationApi:
          Type: Api
          Properties:
            Path: /relations/search_user_relation/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  GetRelationInvitesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/relations/get_relation_invites/
      Handler: get_relation_invites.get_relation_invites
      Events:
        GetRelationInvitesApi:
          Type: Api
          Properties:
            Path: /relations/get_relation_invites/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  GetMutualUserRelationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/relations/get_mutual_user_relations/
      Handler: get_mutual_user_relations.get_mutual_user_relations
      Events:
        GetMutualUserRelationsApi:
          Type: Api
          Properties:
            Path: /relations/get_mutual_user_relations/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  RemoveUserRelationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/relations/remove_user_relation/
      Handler: remove_user_relation.remove_user_relation
      Events:
        RemoveUserRelationApi:
          Type: Api
          Properties:
            Path: /relations/remove_user_relation/
            Method: delete
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  GetRelationInvitesCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/relations/get_relation_invites_count/
      Handler: get_relation_invites_count.get_relation_invites_count
      Events:
        GetRelationInvitesCountApi:
          Type: Api
          Properties:
            Path: /relations/get_relation_invites_count/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer

  #
  #
  #
  # GRAPH FUNCTIONS
  #
  #
  #
  GetWorkRestRatioFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/graph/get_work_rest_ratio/
      Handler: get_work_rest_ratio.get_work_rest_ratio
      Events:
        GetWorkRestRatioApi:
          Type: Api
          Properties:
            Path: /graph/get_work_rest_ratio/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer
  GetAvgVelocityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/graph/get_avg_velocity/
      Handler: get_avg_velocity.get_avg_velocity
      Events:
        GetAvgVelocityApi:
          Type: Api
          Properties:
            Path: /graph/get_avg_velocity/
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: RDSLayer
        - Ref: UserAuthLayer