
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowHeaders: "'Content-Type, Authorization'"
        AllowOrigin: "'http://localhost:8081'"
        AllowCredentials: true

  DynamoDBLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: DynamoDBLayer
        Description: DynamoDBLayer utilities
        ContentUri: layers/common/python/
        CompatibleRuntimes:
          - python3.12
      Metadata:
        BuildMethod: python3.12
  RDSLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: RDSLayer
        Description: RDSLayer utilities
        ContentUri: layers/common/python/
        CompatibleRuntimes:
          - python3.12
      Metadata:
        BuildMethod: python3.12

  CreateAthleteFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambdas/athlete/create_athlete/
      Handler: create_athlete.create_athlete
      Runtime: python3.12
      Timeout: 15
      Environment:
        Variables:
          DYNAMODB_ENDPOINT_URL: http://host.docker.internal:8000
      Events:
        CreateAthleteApi:
          Type: Api
          Properties:
            Path: /athletes/create_athlete/
            Method: post
            RestApiId: !Ref ApiGatewayApi
      Layers:
        - Ref: DynamoDBLayer